### ISSUE TITLE
Bug: 使用指令时报错

### ISSUE THREAD

**Issue by takaqiao** [AwesomeHamster/koishi-plugin-ffxiv-macrodict#4]
`app TypeError: unknown field "Alias_de" in model macrodict
                            at D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\minato\lib\node.js:286:17
                            at Array.map (<anonymous>)
                            at Model.format (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\minato\lib\node.js:277:28)
                            at D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\minato\lib\node.js:557:45
                            at Array.map (<anonymous>)
                            at DatabaseService.upsert (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\minato\lib\node.js:557:21)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async Ne.update (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\koishi-plugin-ffxiv-macrodict\dist\index.bundle.js:3:15353)`

**Comment by takaqiao** [comment]
`command macrodict
                        TypeError: Cannot read properties of undefined (reading 'startsWith')
                            at _Command.<anonymous> (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\koishi-plugin-ffxiv-macrodict\dist\index.bundle.js:30:860)
                            at Array.<anonymous> (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1055:27)
                            at Object.argv.next (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1067:60)
                            at _Command.execute (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1070:33)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1669:22
                            at async Session.withScope (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1559:14)
                            at async next (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:2116:16)
                            at async next (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:2116:16)
                            at async next (D:\Stuffs\ForkyKoishiRetest\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:2116:16)`

**Comment by MaikoTan** [comment]
It is not very clear of your issue, could you provide some information as following?

- Which command did you use?
- Which version of koishi and koishi-plugin-ffxiv-macrodict are you using?
- Which database are you using? Also which version?
- Have you tried `/macrodict.update`? And what is the output in your terminal?

**Comment by takaqiao** [comment]
> It is not very clear of your issue, could you provide some information as following?
> 
> * Which command did you use?
> * Which version of koishi and koishi-plugin-ffxiv-macrodict are you using?
> * Which database are you using? Also which version?
> * Have you tried `/macrodict.update`? And what is the output in your terminal?

1.macrodict and /macrodict.update has caused those errors
2.Im using the newest 4.7.4 koishi and 2.0.7 macrodict
3.Im using sqlite and its 1.3.2
4.When using macrodict 'macrodict'
`command macrodict
                        TypeError: Cannot read properties of undefined (reading 'startsWith')
                            at _Command.<anonymous> (C:\ForkyKoishi\node_modules\koishi-plugin-ffxiv-macrodict\dist\index.bundle.js:30:860)
                            at Array.<anonymous> (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1055:27)
                            at Object.argv.next (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1067:60)
                            at _Command.execute (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1070:33)
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1669:22
                            at async Session.withScope (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1559:14)
                            at async next (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:2116:16)
                            at async next (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:2116:16)`
When using macrodict.update
`command macrodict
                        TypeError: Cannot read properties of undefined (reading 'startsWith')
                            at _Command.<anonymous> (C:\ForkyKoishi\node_modules\koishi-plugin-ffxiv-macrodict\dist\index.bundle.js:30:860)
                            at Array.<anonymous> (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1055:27)
                            at Object.argv.next (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1067:60)
                            at _Command.execute (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1070:33)
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1669:22
                            at async Session.withScope (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1559:14)
                            at async next (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:2116:16)
                            at async next (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:2116:16)`
also I think its irrelevent but I didnt add any prefix to my commands.So its just basicly 'macrodict'not'/macrodict'
![image](https://user-images.githubusercontent.com/13859193/173785375-a7247445-5bf1-4b18-b2a7-0fc264caee3a.png)

**Comment by takaqiao** [comment]
btw,what should I put into alias? Cuz I just random put some words into it before and when I delete them the errors seem to get different somehow?
`2022-06-15 16:58:20 [I] app reload plugin ffxiv-macrodict
2022-06-15 16:58:20 [I] sqlite auto updating table macrodict
2022-06-15 17:01:01 [W] sqlite SQL > INSERT INTO `stats_daily` (`command`,`dialogue`,`botSend`,`botReceive`,`group`,`time`) VALUES ('{"broadcast":1,"macrodict":3}', '{}', '{"discord:985209419681898566":11,"onebot:2669179369":4}', '{"discord:985209419681898566":25,"onebot:2669179369":2}', '{"discord:985210062568034375":5,"onebot:758375829":4,"discord:985161457316536400":6}', 1655222400000)
2022-06-15 17:01:01 [W] sqlite SQL > INSERT INTO `stats_longterm` (`message`,`time`) VALUES (15, 1655222400000)
2022-06-15 17:01:01 [W] command macrodict
                        TypeError: Cannot read properties of undefined (reading 'startsWith')
                            at _Command.<anonymous> (C:\ForkyKoishi\node_modules\koishi-plugin-ffxiv-macrodict\dist\index.bundle.js:30:860)
                            at Array.<anonymous> (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1055:27)
                            at Object.argv.next (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1067:60)
                            at _Command.execute (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1070:33)
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1669:22
                            at async Session.withScope (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:1559:14)
                            at async next (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:2116:16)
                            at async next (C:\ForkyKoishi\node_modules\@koishijs\core\lib\node.js:2116:16)
2022-06-15 17:01:01 [W] app SqliteError: UNIQUE constraint failed: stats_daily.time
                            at SQLiteDriver._SQLiteDriver_exec (C:\ForkyKoishi\node_modules\@minatojs\driver-sqlite\lib\index.js:240:52)
                            at SQLiteDriver._SQLiteDriver_create (C:\ForkyKoishi\node_modules\@minatojs\driver-sqlite\lib\index.js:259:91)
                            at SQLiteDriver.upsert (C:\ForkyKoishi\node_modules\@minatojs\driver-sqlite\lib\index.js:231:98)
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async DatabaseService.upsert (C:\ForkyKoishi\node_modules\minato\lib\node.js:559:5)
                            at async _StatisticsProvider._uploadDaily (C:\ForkyKoishi\node_modules\@koishijs\plugin-status\lib\index.js:346:5)
                            at async Promise.all (index 0)
                            at async _StatisticsProvider.upload (C:\ForkyKoishi\node_modules\@koishijs\plugin-status\lib\index.js:392:7)`

**Comment by MaikoTan** [comment]
First, `macrodict` command is used for read the description of a specific macro, so you should append a macro when you are using the `macrodict` command, like `macrodict hotbar` if you want to read the description of the `hotbar` macro.
Then, according to your log, you have connecting issues on the Discord adapter, so that the plugin didn't response at all.

Also, as an FYI, this plugin **MUST** update all the data before using it, otherwise it would just report errors.
You can see the log that says `macrodict: start updating macros`, and when it is done, it should also produce a long says `macrodict: macros updated`. Have you seen this log before using it?

------

RE: prefixes question
If you have the prefix settings configured in your koishi.yml (or Global Settings in the Koishi Console), then you must prepend the prefix that you set; Otherwise you can call the command without any prefix.

**Comment by takaqiao** [comment]
> First, `macrodict` command is used for read the description of a specific macro, so you should append a macro when you are using the `macrodict` command, like `macrodict hotbar` if you want to read the description of the `hotbar` macro.
> Then, according to your log, you have connecting issues on the Discord adapter, so that the plugin didn't response at all.

I see:)its a stupid question

> Also, as an FYI, this plugin **MUST** update all the data before using it, otherwise it would just report errors.
> You can see the log that says `macrodict: start updating macros`, and when it is done, it should also produce a long says `macrodict: macros updated`. Have you seen this log before using it?

nope. not at all
![image](https://user-images.githubusercontent.com/13859193/173799730-33577da4-86d2-4a7b-92c0-7edeb69468e4.png)
`2022-06-15 17:54:14 [D] message [FF14各种窝窝头测试] taka_qiao: macrodict.update
2022-06-15 17:54:14 [W] i18n missing commands.macrodict.update.messages.start_updating_macros
2022-06-15 17:54:14 [I] macrodict start updating macros
2022-06-15 17:54:33 [W] app TypeError: unknown field "Alias_de" in model macrodict
                            at C:\ForkyKoishi\node_modules\minato\lib\node.js:286:17
                            at Array.map (<anonymous>)
                            at Model.format (C:\ForkyKoishi\node_modules\minato\lib\node.js:277:28)
                            at C:\ForkyKoishi\node_modules\minato\lib\node.js:557:45
                            at Array.map (<anonymous>)
                            at DatabaseService.upsert (C:\ForkyKoishi\node_modules\minato\lib\node.js:557:21)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async Ne.update (C:\ForkyKoishi\node_modules\koishi-plugin-ffxiv-macrodict\dist\index.bundle.js:3:15353)`


> RE: prefixes question
> If you have the prefix settings configured in your koishi.yml (or Global Settings in the Koishi Console), then you must prepend the prefix that you set; Otherwise you can call the command without any prefix.

Thx for mention that.just testing so I havent add any prefix yet

**Comment by MaikoTan** [comment]
```log
[W] app TypeError: unknown field "Alias_de" in model macrodict
        at /home/***/workspaces/koishi-app/node_modules/minato/lib/node.js:286:17
        at Array.map (<anonymous>)
        at Model.format (/home/***/workspaces/koishi-app/node_modules/minato/lib/node.js:277:28)
        at /home/***/workspaces/koishi-app/node_modules/minato/lib/node.js:557:45
        at Array.map (<anonymous>)
        at DatabaseService.upsert (/home/***/workspaces/koishi-app/node_modules/minato/lib/node.js:557:21)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Ne.update (/home/***/workspaces/koishi-app/node_modules/koishi-plugin-ffxiv-macrodict/dist/index.bundle.js:3:15353)
```

I can reproduce this error only, I think there are bugs on database initialiation.
Will fix in the next release.

**Comment by takaqiao** [comment]
> ```
> [W] app TypeError: unknown field "Alias_de" in model macrodict
>         at /home/***/workspaces/koishi-app/node_modules/minato/lib/node.js:286:17
>         at Array.map (<anonymous>)
>         at Model.format (/home/***/workspaces/koishi-app/node_modules/minato/lib/node.js:277:28)
>         at /home/***/workspaces/koishi-app/node_modules/minato/lib/node.js:557:45
>         at Array.map (<anonymous>)
>         at DatabaseService.upsert (/home/***/workspaces/koishi-app/node_modules/minato/lib/node.js:557:21)
>         at processTicksAndRejections (node:internal/process/task_queues:96:5)
>         at async Ne.update (/home/***/workspaces/koishi-app/node_modules/koishi-plugin-ffxiv-macrodict/dist/index.bundle.js:3:15353)
> ```
> 
> I can reproduce this error only, I think there are bugs on database initialiation. Will fix in the next release.

Appreciated:)

**Comment by MaikoTan** [comment]
@takaqiao You can now update the plugin to 2.0.9, see if the problem was solved.
I can't reproduce it after that.

-------

If still you can reproduce it, please leave all the information of your environment.

**Comment by MaikoTan** [comment]
Closed as not active for a long time, if the issue still occurred, you can open a new issue for that.
